ACCOUNT_SAVER = "SAVER"
ACCOUNT_TRANSACTIONAL = "TRANSACTIONAL"

BASE_URL = "https://api.up.com.au/api/v1"

TRANSACTION_HELD = "HELD"
TRANSACTION_SETTLED = "SETTLED"

DEFAULT_PAGE_SIZE = 20
DEFAULT_LIMIT = 20
