name: "Get and update metadata"
description: ""
outputs:
  python:
    description: "Python Version"
    value: ${{ steps.metadata.outputs.python }}
runs:
  using: "composite"
  steps:
    - id: metadata
      shell: bash
      run: |
        echo ::set-output name=python::$(cat setup.cfg | grep -oE 'python_requires = .+?([0-9.]+)' | cut -d "=" -f 3)
        echo "description = ${{ github.event.repository.description }}" >> setup.cfg
